version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    container_name: gymshare_backend
    restart: always
    build: 
      context: ./backend
    command: bash -c "python manage.py collectstatic --clear --noinput && python manage.py migrate && python manage.py initaccounts && gunicorn gymshareapi.wsgi:application -w 2 -b :8000 --reload"
    volumes:
      - ./backend:/backend
      - static_volume:/backend/staticfiles
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/backend/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: